### ISSUE TITLE
Can support MSIs not on nodepool VMSS?

### ISSUE THREAD

**Issue by rakelkar** [Azure/msi-acrpull#38]
My understanding is that AAD pod identity can resolve any MSI that is in an RG for which the cluster identity has the identity operator role. See https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/

```
az role assignment create --role "Managed Identity Operator" --assignee <ID> --scope /subscriptions/<SubscriptionID>/resourcegroups/<IdentityResourceGroup>
```

Does msi-acrpull also work this way? The readme appears to note that the MSI needs to be explicitly added to the nodepool VMSS. 

Thinking about this some more, the nodepool approach has the advantage of limiting the access scope of the MSI to the nodepool. Maybe the best of both worlds would be if the nodepool MSI could optionally resolve MSIs that are in RG for which it has Managed Identity Operator role 

:-)

**Comment by rakelkar** [comment]
Actually can you clarify which nodepool the comment refers to? The one that the deployment pods run or is it the node that the controller runs on... if it is the latter I guess that gives the entire cluster access to the entire set of identities right? (in which case my comment about access being scoped is invalid)

**Comment by weng271190436** [comment]
> Actually can you clarify which nodepool the comment refers to? The one that the deployment pods run or is it the node that the controller runs on... if it is the latter I guess that gives the entire cluster access to the entire set of identities right? (in which case my comment about access being scoped is invalid)

The nodepool is the node that the controller runs on. And yes the entire cluster will be able to use the MSIs to generate image pull secrets.



> My understanding is that AAD pod identity can resolve any MSI that is in an RG for which the cluster identity has the identity operator role. See https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/
> 
> ```
> az role assignment create --role "Managed Identity Operator" --assignee <ID> --scope /subscriptions/<SubscriptionID>/resourcegroups/<IdentityResourceGroup>
> ```
> 
> Does msi-acrpull also work this way? The readme appears to note that the MSI needs to be explicitly added to the nodepool VMSS.
> 
> Thinking about this some more, the nodepool approach has the advantage of limiting the access scope of the MSI to the nodepool. Maybe the best of both worlds would be if the nodepool MSI could optionally resolve MSIs that are in RG for which it has Managed Identity Operator role
> 
> :-)

msi-acrpull and aad-pod-identity work in different ways. aad-pod-identity needs to have "Managed Identity Operator" role because it assigns/removes the MSIs to/from the nodepools dynamically. msi-acrpull doesn't do this.

**Comment by rakelkar** [comment]
> because it assigns/removes the MSIs to/from the nodepools dynamically
So if I were to use both AAD Pod Id and this MSI-ACR pull would I be able to use the former to add MSI to the nodepool and then use the latter to use the newly added MSI to pull from ACR?

**Comment by weng271190436** [comment]
> > because it assigns/removes the MSIs to/from the nodepools dynamically
> 
> So if I were to use both AAD Pod Id and this MSI-ACR pull would I be able to use the former to add MSI to the nodepool and then use the latter to use the newly added MSI to pull from ACR?

I think it would work. As long as you created the correct AzureIdentity and AzureIdentityBinding before you create your AcrPullBinding because the correct AzureIdentity and AzureIdentiyBinding will signal aad-pod-identity to assign the correct MSI on the agent pool.

But it is important to note that aad-pod-identity intercept the call to get ARM token from IMDS endpoint so you should apply AzurePodIdentityException on the msi-acrpull pods

https://azure.github.io/aad-pod-identity/docs/configure/application_exception/

**Comment by stevekuznetsov** [comment]
Seems like the question got answered here, closing.
